services:
  mqtrader:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      STRATEGY_CONFIG: "/app/config/libmq_demo_strategy.json"  # 容器内的路径
      STRATEGY_LIB: "/app/strategies/libmq_demo_strategy"  # 容器内的路径
    volumes:
      - ./config:/app/config:ro  # 将主机的 config 目录挂载到容器的 /app/config 目录，确保容器可以读取配置文件
      - ./strategies:/app/strategies:ro  # 将主机的 strategies 目录挂载到容器的 /app/strategies 目录，确保容器可以读取动态库
