# Cargo config file. 
# See: https://doc.rust-lang.org/cargo/reference/config.html

# Environments variables set for all `cargo ...` commands.
[env]

# Scope down tracing, to filter out external lib tracing.
RUST_LOG="mqtrader=info"

# -- Service Environment Variables
# IMPORTANT: 
#   For cargo commands only.
#   For deployed env, should be managed by container 
#   (e.g., Kubernetes).

## -- Secrets
# Keys and passwords below are for localhost dev ONLY.
# e.g., "welcome" type of passwords.
# i.e., Encryption not needed.
# mqtrader
STRATEGY_CONFIG = "./config/libmq_demo_strategy.json"  # 容器内的路径
STRATEGY_LIB = "./strategies/libmq_demo_strategy"  # 容器内的路径
WEBSOCKET_PROXY_ENABLED= "true"  # false 禁用代理 true 开启代理
WEBSOCKET_PROXY_ADDR = "localhost:8888"

