[package]
name = "mqtrader-bot"
version = "0.1.0"
edition = "2024"


[dependencies]
# -- App Libs
lib-auth = { git = "https://github.com/mountainsea-lab/mount-infra.git", branch = "main", package = "lib-auth" }
lib-utils = { git = "https://github.com/mountainsea-lab/mount-infra.git", branch = "main", package = "lib-utils" }
lib-core = { git = "https://github.com/mountainsea-lab/mount-infra.git", branch = "main", package = "lib-core" }

# -- Async
tokio = { workspace = true }
tokio-stream = { version = "0.1.18", features = ["sync"] }
once_cell = { workspace = true }
# -- Json
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_with = { workspace = true }
# -- Web
axum = { workspace = true, features = ["json", "macros"] }
tower-http = { workspace = true , features = ["cors"] }
# -- Data
sqlx = { workspace = true }
sea-query = { workspace = true, features = ["with-rust_decimal","with-json"] }
sea-query-binder = { workspace = true, features = ["with-rust_decimal","with-json"] }
modql = { workspace = true }
rust_decimal = { workspace = true, features = ["serde"] }
rust_decimal_macros = "1.39.0"
arraydeque = { version = "0.5.1"}

# -- Tracing
#tracing = { workspace = true }
#tracing-subscriber = { workspace = true }
ms-tracing ={ git = "https://github.com/mountainsea-lab/ms-tracing.git", branch = "main", version = "0.1.6"}

# -- Others
derive_more = { workspace = true }
uuid = { workspace = true, features = ["serde"] }
# --Error
thiserror = {workspace = true}
async-trait = {workspace = true}

# --Time
time = {workspace = true}

## --Nautilus Trader -online
# 系统核心组件
nautilus-system = { git = "https://github.com/nautechsystems/nautilus_trader.git" }
nautilus-trading = { git = "https://github.com/nautechsystems/nautilus_trader.git" }
nautilus-live = { git = "https://github.com/nautechsystems/nautilus_trader.git"}

# 基础组件
nautilus-common = { git = "https://github.com/nautechsystems/nautilus_trader.git"}
nautilus-model = { git = "https://github.com/nautechsystems/nautilus_trader.git"}
nautilus-core = { git = "https://github.com/nautechsystems/nautilus_trader.git"}
nautilus-data = { git = "https://github.com/nautechsystems/nautilus_trader.git"}
nautilus-portfolio = { git = "https://github.com/nautechsystems/nautilus_trader.git"}

# 指标
nautilus-indicators = { git = "https://github.com/nautechsystems/nautilus_trader.git"}

# 交易所适配库
nautilus-okx = { git = "https://github.com/nautechsystems/nautilus_trader.git"}


# Barter Ecosystem

anyhow = "^1.0.102"
futures-util = "0.3.32"
futures = "0.3.32"
ahash = { version = "0.8.12", features = ["serde"] }
ustr = { version = "1.1.0", features = ["serde"] }
log = "0.4.29"
rstest = "0.26.1"

[dev-dependencies]
serial_test = "3"

[lints]
workspace = true

